### ISSUE TITLE
How to adapt to different sampling points caused by different moving speed

### ISSUE THREAD

**Issue by weir12** [Psy-Fer/deeplexicon#11]
Hi:
Thank you for developing this software.
I have a question about the internal details.
We know that the dwell time of nanopore sequencing is not unstable.
Therefore, the raw sample number of Squiggle corresponding to the same adapter is also inconsistent.
Is there any downsample/upsample processing for the extracted electrical signal before converting to 2D image data?
Or other Data reshaping/Preprocessing？
Thank you. I appreciate your help.

**Comment by noncodo** [comment]
We spent a significant amount of effort investigating this point. Firstly, the extraction of signal is a dynamic process that identifies the characteristic shifts in current between a DNA adapter and its RNA template. 
Secondly, we tested the effect of including additional 'buffer' signal after the cut sites, which was marginal. We concluded that the entailing neuralnet was discriminate enough to handle partial/superfluous signals.
If you want to, you can subtract|add additional time points to the `begin`|`end` cut site variables on line 106 of scripts/dRNA_segmenter.py to play around with this yourself.
You can also look at the source code in /segmentation for more details and other strategies we tested.

**Comment by N-damo** [comment]
> We spent a significant amount of effort investigating this point. Firstly, the extraction of signal is a dynamic process that identifies the characteristic shifts in current between a DNA adapter and its RNA template. Secondly, we tested the effect of including additional 'buffer' signal after the cut sites, which was marginal. We concluded that the entailing neuralnet was discriminate enough to handle partial/superfluous signals. If you want to, you can subtract|add additional time points to the `begin`|`end` cut site variables on line 106 of scripts/dRNA_segmenter.py to play around with this yourself. You can also look at the source code in /segmentation for more details and other strategies we tested.

i suggest that the end-to-end 1D convolution model without losing information in 2D imaging will resolve the different moving speed
