### ISSUE TITLE
empty output after 1 day

### ISSUE THREAD

**Issue by amitblum** [Psy-Fer/deeplexicon#12]
Hello,
Thanks for you useful tool.
I am running my sample with yo recommended command:
deeplexicon.py  -p /L821_BC1_4/BCs1_4/20200923_1453_MN34379_FAO02325_d4e35397/fast5 -f multi -m models/resnet20-final.h5 > deeplexicon_output.tsv

However, it is running for more than 1 day, but my output file is still empty. 
Is it expected to have empty file in such point? 

Thanks
Amit

**Comment by Psy-Fer** [comment]
hello,

It may take a while depending on the hardware it is running on.
A simple test is to copy a single pass multi-fast5 file to it's own folder. Then point the -p flag to that folder, so it processes those 4000 reads. That way you can see if it is working. You should get output as each fast5 file is processed, though that can take a while on slower hardware.

Cheers,
James

**Comment by enovoa** [comment]
I assume this was solved, otherwise please open again, thanks!
