### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by Qiongyi** [Psy-Fer/deeplexicon#13]
Hi,

Thanks for your tool.
I tried to use deeplexicon to demultiplex my samples from a nanopore Mk1c run, but received error messages about  "AttributeError: 'str' object has no attribute 'decode'". All dependencies look good. I have discussed with Martin but we are not quite sure what caused this problem. Please help. I listed my command and the error messages below:

# My command
(deeplexicon) [uqqzhao@inode2 deeplexicon]$ python deeplexicon.py -p 20201219_0616_MC-110494_0_FAK95916_1e4f2d65/fast5_pass -f multi -m models/resnet20-final.h5 > output.tsv

# Error messages
Using TensorFlow backend.
Traceback (most recent call last):
 File "deeplexicon.py", line 622, in <module>
  main()
 File "deeplexicon.py", line 227, in main
  model = read_model(config[deeplexicon][trained_model]) if args.config else read_model(args.model)
 File "deeplexicon.py", line 132, in read_model
  model = load_model(model_name) # as a path
 File "/illumina/tools/deeplexicon/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
  model = _deserialize_model(f, custom_objects, compile)
 File "/illumina/tools/deeplexicon/lib/python3.6/site-packages/keras/engine/saving.py", line 224, in _deserialize_model
  model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'

# Dependencies
(deeplexicon) [uqqzhao@inode2 deeplexicon]$ pip install Keras==2.2.4 Pandas PyTs==0.8.0 Scikit-learn numba==0.45.0 TensorFlow==1.13.1
Requirement already satisfied: Keras==2.2.4 in ./lib/python3.7/site-packages (2.2.4)
Requirement already satisfied: Pandas in ./lib/python3.7/site-packages (1.2.0)
Requirement already satisfied: PyTs==0.8.0 in ./lib/python3.7/site-packages (0.8.0)
Requirement already satisfied: Scikit-learn in ./lib/python3.7/site-packages (0.24.0)
Requirement already satisfied: numba==0.45.0 in ./lib/python3.7/site-packages (0.45.0)
Requirement already satisfied: TensorFlow==1.13.1 in ./lib/python3.7/site-packages (1.13.1)
Requirement already satisfied: numpy>=1.9.1 in ./lib/python3.7/site-packages (from Keras==2.2.4) (1.19.5)
Requirement already satisfied: h5py in ./lib/python3.7/site-packages (from Keras==2.2.4) (3.1.0)
Requirement already satisfied: scipy>=0.14 in ./lib/python3.7/site-packages (from Keras==2.2.4) (1.6.0)
Requirement already satisfied: keras-applications>=1.0.6 in ./lib/python3.7/site-packages (from Keras==2.2.4) (1.0.8)
Requirement already satisfied: pyyaml in ./lib/python3.7/site-packages (from Keras==2.2.4) (5.3.1)
Requirement already satisfied: six>=1.9.0 in ./lib/python3.7/site-packages (from Keras==2.2.4) (1.15.0)
Requirement already satisfied: keras-preprocessing>=1.0.5 in ./lib/python3.7/site-packages (from Keras==2.2.4) (1.1.2)
Requirement already satisfied: llvmlite>=0.29.0dev0 in ./lib/python3.7/site-packages (from numba==0.45.0) (0.32.1)
Requirement already satisfied: astor>=0.6.0 in ./lib/python3.7/site-packages (from TensorFlow==1.13.1) (0.8.1)
Requirement already satisfied: termcolor>=1.1.0 in ./lib/python3.7/site-packages (from TensorFlow==1.13.1) (1.1.0)
Requirement already satisfied: grpcio>=1.8.6 in ./lib/python3.7/site-packages (from TensorFlow==1.13.1) (1.34.0)
Requirement already satisfied: absl-py>=0.1.6 in ./lib/python3.7/site-packages (from TensorFlow==1.13.1) (0.11.0)
Requirement already satisfied: wheel>=0.26 in ./lib/python3.7/site-packages (from TensorFlow==1.13.1) (0.36.2)
Requirement already satisfied: gast>=0.2.0 in ./lib/python3.7/site-packages (from TensorFlow==1.13.1) (0.4.0)
Requirement already satisfied: protobuf>=3.6.1 in ./lib/python3.7/site-packages (from TensorFlow==1.13.1) (3.14.0)
Requirement already satisfied: tensorflow-estimator<1.14.0rc0,>=1.13.0 in ./lib/python3.7/site-packages (from TensorFlow==1.13.1) (1.13.0)
Requirement already satisfied: tensorboard<1.14.0,>=1.13.0 in ./lib/python3.7/site-packages (from TensorFlow==1.13.1) (1.13.1)
Requirement already satisfied: werkzeug>=0.11.15 in ./lib/python3.7/site-packages (from tensorboard<1.14.0,>=1.13.0->TensorFlow==1.13.1) (1.0.1)
Requirement already satisfied: markdown>=2.6.8 in ./lib/python3.7/site-packages (from tensorboard<1.14.0,>=1.13.0->TensorFlow==1.13.1) (3.3.3)
Requirement already satisfied: importlib-metadata in ./lib/python3.7/site-packages (from markdown>=2.6.8->tensorboard<1.14.0,>=1.13.0->TensorFlow==1.13.1) (3.4.0)
Requirement already satisfied: mock>=2.0.0 in ./lib/python3.7/site-packages (from tensorflow-estimator<1.14.0rc0,>=1.13.0->TensorFlow==1.13.1) (4.0.3)
Requirement already satisfied: python-dateutil>=2.7.3 in ./lib/python3.7/site-packages (from Pandas) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in ./lib/python3.7/site-packages (from Pandas) (2020.5)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./lib/python3.7/site-packages (from Scikit-learn) (2.1.0)
Requirement already satisfied: joblib>=0.11 in ./lib/python3.7/site-packages (from Scikit-learn) (1.0.0)
Requirement already satisfied: cached-property in ./lib/python3.7/site-packages (from h5py->Keras==2.2.4) (1.5.2)
Requirement already satisfied: typing-extensions>=3.6.4 in ./lib/python3.7/site-packages (from importlib-metadata->markdown>=2.6.8->tensorboard<1.14.0,>=1.13.0->TensorFlow==1.13.1) (3.7.4.3)
Requirement already satisfied: zipp>=0.5 in ./lib/python3.7/site-packages (from importlib-metadata->markdown>=2.6.8->tensorboard<1.14.0,>=1.13.0->TensorFlow==1.13.1) (3.4.0)

Thanks,

Qiongyi

**Comment by Psy-Fer** [comment]
G'day Qiongyi,

It looks like it is using keras from python 3.6? 
`/illumina/tools/deeplexicon/lib/python3.6/site-packages/keras/engine/saving.py`

But I can see you are using a 3.7 python venv.

The reason 3.6 wasn't working and I moved to 3.7, was specifically because keras is pretty unstable and buggy with these particular tensorflow models. 

A potential solution may be as simple as purging keras and all downloaded data from pip, sourcing the 3.7 venv, and doing a pip install of keras again.

so something like:

repeat this a few times, just to make sure it's all gone
```
pip uninstall Keras
```

then delete the 3.6 libs 

`rm -r /illumina/tools/deeplexicon/lib/python3.6/site-packages/keras/`

Then source deplexicon venv, and install keras again. The pip message shouldn't say it's getting it from an already downloaded source. If it is, make sure your pip is updated so it's working out the versions correctly.

`pip install Keras==2.2.4`

Then try again.

I hope this helps. Keras can be a real pain sometimes.

James

**Comment by Qiongyi** [comment]
Hi James,

Thank you for your prompt reply. I tried Python3.7 but I got many other issues. Google told me Python 3.6 can solve some of these issues so I decided to use Python 3.6 instead of 3.7. 
With this "AttributeError", I was using python 3.6 with the correct 3.6 python venv. However, I pasted here a wrong dependency info from a slack thread discussed with Martin.

# My correct dependency info is shown below:
(deeplexicon) [uqqzhao@inode2 deeplexicon]$ pip install Keras==2.2.4 Pandas PyTs==0.8.0 Scikit-learn numba==0.45.0 TensorFlow==1.13.1
Requirement already satisfied: Keras==2.2.4 in ./lib/python3.6/site-packages (2.2.4)
Requirement already satisfied: Pandas in ./lib/python3.6/site-packages (1.1.5)
Requirement already satisfied: PyTs==0.8.0 in ./lib/python3.6/site-packages (0.8.0)
Requirement already satisfied: Scikit-learn in ./lib/python3.6/site-packages (0.24.0)
Requirement already satisfied: numba==0.45.0 in ./lib/python3.6/site-packages (0.45.0)
Requirement already satisfied: TensorFlow==1.13.1 in ./lib/python3.6/site-packages (1.13.1)
Requirement already satisfied: h5py in ./lib/python3.6/site-packages (from Keras==2.2.4) (3.1.0)
Requirement already satisfied: keras-preprocessing>=1.0.5 in ./lib/python3.6/site-packages (from Keras==2.2.4) (1.1.2)
Requirement already satisfied: numpy>=1.9.1 in ./lib/python3.6/site-packages (from Keras==2.2.4) (1.19.5)
Requirement already satisfied: six>=1.9.0 in ./lib/python3.6/site-packages (from Keras==2.2.4) (1.15.0)
Requirement already satisfied: keras-applications>=1.0.6 in ./lib/python3.6/site-packages (from Keras==2.2.4) (1.0.8)
Requirement already satisfied: pyyaml in ./lib/python3.6/site-packages (from Keras==2.2.4) (5.3.1)
Requirement already satisfied: scipy>=0.14 in ./lib/python3.6/site-packages (from Keras==2.2.4) (1.5.4)
Requirement already satisfied: llvmlite>=0.29.0dev0 in ./lib/python3.6/site-packages (from numba==0.45.0) (0.32.1)
Requirement already satisfied: tensorboard<1.14.0,>=1.13.0 in ./lib/python3.6/site-packages (from TensorFlow==1.13.1) (1.13.1)
Requirement already satisfied: gast>=0.2.0 in ./lib/python3.6/site-packages (from TensorFlow==1.13.1) (0.4.0)
Requirement already satisfied: termcolor>=1.1.0 in ./lib/python3.6/site-packages (from TensorFlow==1.13.1) (1.1.0)
Requirement already satisfied: grpcio>=1.8.6 in ./lib/python3.6/site-packages (from TensorFlow==1.13.1) (1.34.0)
Requirement already satisfied: protobuf>=3.6.1 in ./lib/python3.6/site-packages (from TensorFlow==1.13.1) (3.14.0)
Requirement already satisfied: tensorflow-estimator<1.14.0rc0,>=1.13.0 in ./lib/python3.6/site-packages (from TensorFlow==1.13.1) (1.13.0)
Requirement already satisfied: wheel>=0.26 in ./lib/python3.6/site-packages (from TensorFlow==1.13.1) (0.36.2)
Requirement already satisfied: astor>=0.6.0 in ./lib/python3.6/site-packages (from TensorFlow==1.13.1) (0.8.1)
Requirement already satisfied: absl-py>=0.1.6 in ./lib/python3.6/site-packages (from TensorFlow==1.13.1) (0.11.0)
Requirement already satisfied: werkzeug>=0.11.15 in ./lib/python3.6/site-packages (from tensorboard<1.14.0,>=1.13.0->TensorFlow==1.13.1) (1.0.1)
Requirement already satisfied: markdown>=2.6.8 in ./lib/python3.6/site-packages (from tensorboard<1.14.0,>=1.13.0->TensorFlow==1.13.1) (3.3.3)
Requirement already satisfied: importlib-metadata in ./lib/python3.6/site-packages (from markdown>=2.6.8->tensorboard<1.14.0,>=1.13.0->TensorFlow==1.13.1) (3.4.0)
Requirement already satisfied: mock>=2.0.0 in ./lib/python3.6/site-packages (from tensorflow-estimator<1.14.0rc0,>=1.13.0->TensorFlow==1.13.1) (4.0.3)
Requirement already satisfied: pytz>=2017.2 in ./lib/python3.6/site-packages (from Pandas) (2020.5)
Requirement already satisfied: python-dateutil>=2.7.3 in ./lib/python3.6/site-packages (from Pandas) (2.8.1)
Requirement already satisfied: joblib>=0.11 in ./lib/python3.6/site-packages (from Scikit-learn) (1.0.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./lib/python3.6/site-packages (from Scikit-learn) (2.1.0)
Requirement already satisfied: cached-property in ./lib/python3.6/site-packages (from h5py->Keras==2.2.4) (1.5.2)
Requirement already satisfied: zipp>=0.5 in ./lib/python3.6/site-packages (from importlib-metadata->markdown>=2.6.8->tensorboard<1.14.0,>=1.13.0->TensorFlow==1.13.1) (3.4.0)
Requirement already satisfied: typing-extensions>=3.6.4 in ./lib/python3.6/site-packages (from importlib-metadata->markdown>=2.6.8->tensorboard<1.14.0,>=1.13.0->TensorFlow==1.13.1) (3.7.4.3)


Pip is up to date. Anyway, I will give it a go for Python3.7 again and will let you know if there are any issues.

Cheers,

Qiongyi

**Comment by AminaLEM** [comment]
Hello, 

I have the same problem with Python3.7

Best,

**Comment by Qiongyi** [comment]
Hi AminaLEM,

Just want to let you know that we didn't find a solution for this issue, and ended up using bucket.

Cheers,

Qiongyi

**Comment by lpryszcz** [comment]
same error here (Ubuntu 20.04, Python 3.7.9).

**Comment by lpryszcz** [comment]
ok, so the problem is incompatibility between Keras 2.2.4 and recent version of h5py... the solution is to install h5py==2.10
```bash
pip install h5py==2.10 Keras==2.2.4 Pandas PyTs==0.8.0 Scikit-learn numba TensorFlow==1.13.1
```
