### ISSUE TITLE
can't find example fast5 data

### ISSUE THREAD

**Issue by st-pfister** [Psy-Fer/deeplexicon#16]
hey there, 

I wanted to try out the demultiplexing with the "example fast5 data built using the 4 custom barcoded adaptors" that you wanted to include, but I could not find it. Could you point me into the direction of this data? I would really like to give it a go with this example data!

bests,
stefan

**Comment by enovoa** [comment]
Sorry for slow response. I believe that the current version of the repo doesn't have this example data you mention above. If you need some data to test the algorithm, you can use the following datasets that are published with our work: PRJNA545820. Thanks!
