### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by llllIIIIIllll** [Psy-Fer/deeplexicon#18]
When I run this line of instructions：
python3 deeplexicon.py dmux -p ~/top/fast5/path/ -f multi -m models/resnet20-final.h5 > output.tsv

There are some problems：
Using TensorFlow backend.
error: unrecognized arguments: dmux

I don't know how to solve it.（I'm just a rookie.）
Can someone help me with my puzzle?

**Comment by Psy-Fer** [comment]
Hello,

You will want to use `deeplexicon_sub.py` or `deeplexicon_multi.py` with that command. The base deeplexicon.py command doesn't have sub-modules, and only does demux. So to get it to work with that, remove `dmux`.

Let me know know if you have any more issues.
Cheers
James

**Comment by llllIIIIIllll** [comment]
Thank you!
So,these four files: deeplexicon.py, deeplexicon_multi.py, deeplexicon_sub, pyfastq_splitter.py
What exactly does it do?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Psy-Fer/deeplexicon"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月12日(星期天) 晚上7:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Psy-Fer/deeplexicon] A question (#18)





 
Hello,
 
You will want to use deeplexicon_sub.py or deeplexicon_multi.py with that command. The base deeplexicon.py command doesn't have sub-modules, and only does demux. So to get it to work with that, remove dmux.
 
Let me know know if you have any more issues.
 Cheers
 James
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Psy-Fer** [comment]
`Deeplexicon.py`: The original source file for this project, and the one that was put in the release with the paper. Recently updated, but probably not the best one to use.
`fastq_splitter.py`: reads the output tsv after demultiplexing the fast5 files, and splits the fastq reads by the corresponding barcode using readID
`deeplexicon_sub.py`: Started as the prototype for multiple sub-modules, to allow the user to dmux, train, split, or just extract data from the fat5 files. This was the main release for a user to train their own models. The split sub-module is just the `fastq_splitter.py` code. It was also recently been updated.
`deeplexicon_multi.py`: is a recent update from a colleague, which added multi-processing. Otherwise, it is similar to `deeplexicon_sub.py`.

**Comment by llllIIIIIllll** [comment]
Thank you very much, I will continue to try to study the code, and I may still come to ask if there are any problems


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Psy-Fer/deeplexicon"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月12日(星期天) 晚上8:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Psy-Fer/deeplexicon] A question (#18)





 
Deeplexicon.py: The original source file for this project, and the one that was put in the release with the paper. Recently updated, but probably not the best one to use.
 fastq_splitter.py: reads the output tsv after demultiplexing the fast5 files, and splits the fastq reads by the corresponding barcode using readID
 deeplexicon_sub.py: Started as the prototype for multiple sub-modules, to allow the user to dmux, train, split, or just extract data from the fat5 files. This was the main release for a user to train their own models. The split sub-module is just the fastq_splitter.py code. It was also recently been updated.
 deeplexicon_multi.py: is a recent update from a colleague, which added multi-processing. Otherwise, it is similar to deeplexicon_sub.py.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by llllIIIIIllll** [comment]
I have another question：
&nbsp; &nbsp;&nbsp;When I enter this line of instructions：python3 deeplexicon.py -p ~/top/fast5/path/ -f multi -m models/resnet20-final.h5 &gt; output.tsv
&nbsp; &nbsp;&nbsp;I got an output.tsv file and finished creating the table.
&nbsp; &nbsp;&nbsp;But I got an error：
&nbsp; &nbsp; &nbsp; &nbsp; ValueError: Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (0, 1)
&nbsp; &nbsp;&nbsp;I don't know where to find the fast5 file, and I don't know what this file looks like.
&nbsp; &nbsp;&nbsp;Can you give me an example？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Psy-Fer/deeplexicon"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月12日(星期天) 晚上8:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Psy-Fer/deeplexicon] A question (#18)





 
Deeplexicon.py: The original source file for this project, and the one that was put in the release with the paper. Recently updated, but probably not the best one to use.
 fastq_splitter.py: reads the output tsv after demultiplexing the fast5 files, and splits the fastq reads by the corresponding barcode using readID
 deeplexicon_sub.py: Started as the prototype for multiple sub-modules, to allow the user to dmux, train, split, or just extract data from the fat5 files. This was the main release for a user to train their own models. The split sub-module is just the fastq_splitter.py code. It was also recently been updated.
 deeplexicon_multi.py: is a recent update from a colleague, which added multi-processing. Otherwise, it is similar to deeplexicon_sub.py.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Psy-Fer** [comment]
Hello.

I edited your comment, as there was a lot of HTML code bleeding through.

`-p ~/top/fast5/path/` is meant to be the path to the fast5 files you want to demultiplex. These are the raw signal files that are produced by MinKNOW during a sequencing run, and the same files guppy uses to produce the fastq files.

Deeplexicon is recursive, so it will process any fast5 files under a larger directory structure.

an example might be `-p /data/FVXF260455/cas9_lib1/20210916_0523_X1_AFT097_fa40753d/fast5_pass/` 
This is from one of our runs on a GridION where the default data storage folder for runs is in `/data/`

Does this answer your question?
