### ISSUE TITLE
typo in README? 

### ISSUE THREAD

**Issue by enovoa** [Psy-Fer/deeplexicon#6]
I believe the command: "python3 fastq_splitter.py -d output.txt -q combined.fastq -o dmux_folder/ -s sample_name" should say "output.tsv" instead of "output.txt" (i.e. it is the output of the deeplexicon script in the previous step). To make clear both are the same? thx!

**Comment by Psy-Fer** [comment]
Yep you are correct. I'll update.

**Comment by Psy-Fer** [comment]
Updated. Thanks
