### ISSUE TITLE
about requirements versions

### ISSUE THREAD

**Issue by ygidtu** [Psy-Fer/deeplexicon#7]
The packages installed using the command from README `pip install Keras==2.2.4 Pandas PyTs==0.8.0 Scikit-learn numba==0.45.0 TensorFlow==1.13.1` will cause an expected error `TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug'.`

I could resolve this error by update numba to lastest version. 

Could you please provide the `requirements.txt` or lock file for specific package version?

**Comment by Psy-Fer** [comment]
Hello,

What operating system and python version are you using? I have yet to see this error. Let me know so I can try and reproduce it.

Thanks :)

**Comment by ygidtu** [comment]
It's Ubuntu 16.04 and Python 3.7.6 installed using pyenv (version 1.2.16-5-g7097f82
) with `PYTHON_CONFIGURE_OPTS="--enable-shared"`

**Comment by 690645258** [comment]
I also got this error when running demultiplexing. However `pip install -U llvmlite==0.32.1` as found on [this github issue](https://github.com/mkocabas/VIBE/issues/91) resolved it

**Comment by lpryszcz** [comment]
same issue here, 

- @690645258 solution `pip install -U llvmlite==0.32.1` results in in `Segmentation fault (core dumped)`
- `pip install -U numba` seems working
