### ISSUE TITLE
Dataset for quick testing?

### ISSUE THREAD

**Issue by sysuliujh** [Psy-Fer/deeplexicon#9]
Hello, I just installed the requirements, and I would like to test if it can demultiplex reads correctly. So if there are some test data for that? Several reads are enough.

**Comment by Psy-Fer** [comment]
Hello,
Sure thing. I'll Upload one of the multi-fast5 files to help with this. I'll let you know soon when that's done and how to download it.

**Comment by Psy-Fer** [comment]
Here is a link to a single file (with about 4k files in it)
Put it in a folder by itself, and then use the `-p` to point to that top directory.

Alternatively, use `deeplexicon_sub.py dmux` command to use gpu with `-g` option, if the appropriate libraries are set up. Though CPU calling will work too.
This file will be come the dominant deeplexicon.py file quite soon. I'm just still tinkering with some optimisations.

Let me know if you need anything else

James

**Comment by sysuliujh** [comment]
Thank you. It seems the demultiplex step runs well. I think I need a new machine... I broke our sever (CentOS 7) twice because of glibc update. And it's a bit slow in the step "info: reading sig_count: 1/4000" for single CPU thread (~0.5-1 second per read).

**Comment by Psy-Fer** [comment]
Yea, at single CPU it's a tad slow. Multiple CPU is coming. We have been using array jobs with SGE to run each fast5 file in parallel.

I'm glad it works on your hands, even if it's a bit slow for now.

**Comment by sysuliujh** [comment]
I used my personal computer to do the basecall. The split fastq step goes well.
